# Navigation Links
# The weight parameter defines the order that the links will appear in.
# You can add, remove, or reorder these menu items as needed.

main:
  - name: Home
    url: /
    weight: 10
  - name: Publications
    url: /publication/
    weight: 20
  - name: Projects
    url: /project/
    weight: 30
  - name: Teaching
    url: /teaching/
    weight: 40
  - name: Blog
    url: /post/
    weight: 50
  - name: Experience
    url: /experience/
    weight: 60
  # - name: Contact
  #   url: /contact/
  #   weight: 70
